### ISSUE TITLE
Name or service not known

### ISSUE THREAD

**Issue by vi** [cmol/punchVPN#1]
```
$ python3.4 punchVPN.py  -v --no-vpn 
INFO:PunchVPN:NAT-PMP - Testing for NAT-PMP...    
DEBUG:PunchVPN.nat-pmp:Found gateway 192.168.89.1
DEBUG:PunchVPN.nat-pmp:Gateway 192.168.89.1 does not support nat-pmp
INFO:PunchVPN:NAT-PMP - [FAILED]
INFO:PunchVPN:UPnP-IGD - Testing for UPnP-IDG...
Traceback (most recent call last):
  File "punchVPN.py", line 314, in <module>
    main()
  File "punchVPN.py", line 218, in main
    ip = find_ip(args.address.split(':')[1][2:])
  File "punchVPN.py", line 122, in find_ip
    s_ip.connect((addr, 1234))
socket.gaierror: [Errno -2] Name or service not known
```

Error should be handled better.

**Comment by cmol** [comment]
Thanks for reporting the error. I'll get around to this at some point, but it's been four years since I used this, so I'll need to re-familiarise myself with this.
